Repository micromdm/micromdm, pull requests merged in 2018-05, with the labels that each got.

#407 Update ChangeLog with curated list of recent changes & add commit links
  CHANGELOG.md
Labels: documentation

#405 DEP auto-assignment (v2)
  CHANGELOG.md
  cmd/mdmctl/apply.go
  cmd/mdmctl/apply_dep_autoassigner.go
  cmd/mdmctl/apply_dep_profile.go
  cmd/mdmctl/get.go
  cmd/mdmctl/get_dep_autoassigner.go
  cmd/mdmctl/remove.go
  cmd/mdmctl/remove_dep_autoassigner.go
  cmd/mdmctl/setup.go
  cmd/micromdm/serve.go
  dep/depsync/apply_autoassigner.go
  dep/depsync/client.go
  dep/depsync/config.go
  dep/depsync/depsync.go
  dep/depsync/endpoint.go
  dep/depsync/get_autoassigners.go
  dep/depsync/remove_autoassigners.go
  dep/depsync/server.go
  dep/depsync/service.go
  dep/depsync/syncnow.go
  dep/depsync/transport_http.go
  platform/device/builtin/db.go
Labels: db, dep, enhancement, in-progress

#423 reorganize MDM service into a single package.
  Gopkg.lock
  Gopkg.toml
  cmd/micromdm/serve.go
  mdm/acknowledge.go
  mdm/acknowledge_event.go
  mdm/checkin.go
  mdm/checkin/checkin.go
  mdm/checkin/checkin_test.go
  mdm/checkin/endpoint.go
  mdm/checkin/event_test.go
  mdm/checkin/internal/checkinproto/checkin.pb.go
  mdm/checkin/service.go
  mdm/checkin/testdata/Authenticate.plist
  mdm/checkin/testdata/CheckOut.plist
  mdm/checkin/testdata/TokenUpdate.plist
  mdm/checkin/transport_http.go
  mdm/checkin_event.go
  mdm/connect/connect.go
  mdm/connect/endpoint.go
  mdm/connect/internal/connectproto/connect.pb.go
  mdm/connect/middleware.go
  mdm/connect/transport_http.go
  mdm/internal/checkinproto/checkin.go
  mdm/internal/checkinproto/checkin.pb.go
  mdm/internal/checkinproto/checkin.proto
  mdm/internal/connectproto/connect.go
  mdm/internal/connectproto/connect.pb.go
  mdm/internal/connectproto/connect.proto
  mdm/server.go
  mdm/service.go
  platform/apns/builtin/db.go
  platform/blueprint/builtin/listener.go
  platform/device/builtin/db.go
  platform/queue/queue.go
  platform/queue/queue_test.go
  platform/remove/remove.go
  platform/user/builtin/db.go
  workflow/webhook/command.go
Labels: in-progress
